DROP TABLE IF EXISTS github_repo;
DROP TABLE IF EXISTS user_account;

-- =========================
-- USER_ACCOUNT
-- =========================
CREATE TABLE USER_ACCOUNT
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    GITHUB_USER_ID    BIGINT       NOT NULL UNIQUE,
    GITHUB_LOGIN      VARCHAR(100) NOT NULL UNIQUE,
    GITHUB_EMAIL      VARCHAR(150) NULL,
    GITHUB_AVATAR_URL VARCHAR(255) NULL,
    GITHUB_NAME       VARCHAR(100) NULL,
    LAST_SYNCED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IDX_GITHUB_LOGIN
    ON USER_ACCOUNT (GITHUB_LOGIN);

-- =========================
-- GITHUB_REPO
-- =========================
CREATE TABLE GITHUB_REPO
(
    ID                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ACCOUNT_ID       BIGINT       NOT NULL,
    GITHUB_REPO_ID        BIGINT       NOT NULL UNIQUE,
    GITHUB_REPO_NAME      VARCHAR(100) NOT NULL,
    GITHUB_REPO_FULL_NAME VARCHAR(200) NOT NULL UNIQUE,
    DEFAULT_BRANCH        VARCHAR(150) NULL,
    DESCRIPTION           TEXT NULL,
    GITHUB_REPO_URL       VARCHAR(255) NULL,
    IS_PRIVATE            TINYINT(1) NOT NULL DEFAULT 0,
    LAST_SYNCED_AT        TIMESTAMP NULL,
    CREATED_AT            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT            TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_GITHUB_REPOSITORY_OWNER
        FOREIGN KEY (USER_ACCOUNT_ID)
            REFERENCES USER_ACCOUNT (ID)
            ON DELETE CASCADE
);

CREATE INDEX IDX_REPOSITORY_OWNER
    ON GITHUB_REPO (USER_ACCOUNT_ID);

CREATE INDEX IDX_REPOSITORY_SYNC_TIME
    ON GITHUB_REPO (LAST_SYNCED_AT);
