-- BATCH_JOB_INSTANCE
CREATE TABLE BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VERSION BIGINT,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
) ENGINE=InnoDB;

-- BATCH_JOB_EXECUTION
CREATE TABLE BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP(6) NOT NULL,
    START_TIME TIMESTAMP(6) NULL DEFAULT NULL,
    END_TIME TIMESTAMP(6) NULL DEFAULT NULL,
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP(6) NULL DEFAULT NULL,
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
        REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ENGINE=InnoDB;

-- BATCH_JOB_EXECUTION_PARAMS
CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_TYPE VARCHAR(100) NOT NULL,
    PARAMETER_VALUE VARCHAR(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB;

-- BATCH_STEP_EXECUTION
CREATE TABLE BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP(6) NOT NULL,
    START_TIME TIMESTAMP(6) NULL DEFAULT NULL,
    END_TIME TIMESTAMP(6) NULL DEFAULT NULL,
    STATUS VARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP(6) NULL DEFAULT NULL,
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB;

-- BATCH_STEP_EXECUTION_CONTEXT
CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
        REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ENGINE=InnoDB;

-- BATCH_JOB_EXECUTION_CONTEXT
CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB;

-- user_account
CREATE TABLE user_account (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    github_user_id BIGINT NOT NULL UNIQUE,
    github_login VARCHAR(100) NOT NULL UNIQUE,
    github_email VARCHAR(150) NULL,
    github_avatar_url VARCHAR(255) NULL,
    github_name VARCHAR(100) NULL,
    last_synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX idx_github_login ON user_account(github_login);

-- access_token
CREATE TABLE access_token (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_account_id BIGINT NOT NULL,
    access_token VARCHAR(255) NOT NULL UNIQUE,
    token_type VARCHAR(20) DEFAULT 'BEARER',
    scope VARCHAR(500) NULL,
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_access_token_user FOREIGN KEY (user_account_id)
        REFERENCES user_account(id) ON DELETE CASCADE
);

CREATE INDEX idx_token_user ON access_token(user_account_id);

-- github_repo
CREATE TABLE github_repo (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_account_id BIGINT NOT NULL,
    github_repo_id BIGINT NOT NULL UNIQUE,
    github_repo_name VARCHAR(100) NOT NULL,
    github_repo_full_name VARCHAR(200) NOT NULL UNIQUE,
    default_branch VARCHAR(150) NULL,
    description TEXT NULL,
    github_repo_url VARCHAR(255) NULL,
    is_private TINYINT(1) NOT NULL DEFAULT 0,
    last_synced_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_github_repository_owner FOREIGN KEY (user_account_id)
        REFERENCES user_account(id) ON DELETE CASCADE
);

CREATE INDEX idx_repository_owner ON github_repo(user_account_id);
CREATE INDEX idx_repository_sync_time ON github_repo(last_synced_at);

-- commit_log
CREATE TABLE commit_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    github_repo_id BIGINT NOT NULL,
    user_account_id BIGINT NOT NULL,
    github_commit_sha CHAR(40) NOT NULL,
    committed_at TIMESTAMP NOT NULL,
    message TEXT NOT NULL,
    html_url VARCHAR(255) NULL,
    additions BIGINT DEFAULT 0,
    deletions BIGINT DEFAULT 0,
    total_changes BIGINT DEFAULT 0,
    files_changed BIGINT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_commit_repo FOREIGN KEY (github_repo_id)
        REFERENCES github_repo(id) ON DELETE CASCADE,
    CONSTRAINT fk_commit_author FOREIGN KEY (user_account_id)
        REFERENCES user_account(id) ON DELETE CASCADE,
    CONSTRAINT uk_commit_repo_sha UNIQUE (github_repo_id, github_commit_sha)
);

CREATE INDEX idx_commit_author_time ON commit_log(user_account_id, committed_at);
CREATE INDEX idx_commit_repo_time ON commit_log(github_repo_id, committed_at);

-- commit_file_change
CREATE TABLE commit_file_change (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    commit_log_id BIGINT NOT NULL,
    filename VARCHAR(500) NOT NULL,
    prev_filename VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL,
    additions BIGINT NOT NULL DEFAULT 0,
    deletions BIGINT NOT NULL DEFAULT 0,
    changes BIGINT NOT NULL DEFAULT 0,
    patch LONGTEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_commit_file_commit FOREIGN KEY (commit_log_id)
        REFERENCES commit_log(id) ON DELETE CASCADE,
    CONSTRAINT chk_file_status CHECK (status IN ('ADDED','MODIFIED','REMOVED','RENAMED'))
);

CREATE INDEX idx_file_commit ON commit_file_change(commit_log_id);
CREATE INDEX idx_file_filename ON commit_file_change(filename);

-- commit_analysis
CREATE TABLE commit_analysis (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    commit_log_id BIGINT NOT NULL UNIQUE,
    flagged_count BIGINT NOT NULL DEFAULT 0,
    swear_count BIGINT NOT NULL DEFAULT 0,
    exclaim_count BIGINT NOT NULL DEFAULT 0,
    emoji_count BIGINT NOT NULL DEFAULT 0,
    sentiment VARCHAR(20) NULL,
    sentiment_score DECIMAL(5,2) NULL,
    analyzed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_commit_analysis_commit FOREIGN KEY (commit_log_id)
        REFERENCES commit_log(id) ON DELETE CASCADE,
    CONSTRAINT chk_sentiment CHECK (sentiment IN ('POSITIVE','NEUTRAL','NEGATIVE'))
);

-- flagged_token
CREATE TABLE flagged_token (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    commit_log_id BIGINT NOT NULL,
    token VARCHAR(200) NOT NULL,
    token_type VARCHAR(20) NOT NULL DEFAULT 'OTHER',
    weight BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_flagged_token_commit FOREIGN KEY (commit_log_id)
        REFERENCES commit_log(id) ON DELETE CASCADE,
    CONSTRAINT uk_commit_token UNIQUE (commit_log_id, token, token_type),
    CONSTRAINT chk_token_type CHECK (token_type IN ('SWEAR','SLANG','EMOJI','EMPHASIS','OTHER'))
);

CREATE INDEX idx_flagged_commit ON flagged_token(commit_log_id);
CREATE INDEX idx_flagged_token_type ON flagged_token(token_type);

-- refresh_token
CREATE TABLE refresh_token (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_account_id BIGINT NOT NULL,
    token VARCHAR(500) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_account_id)
        REFERENCES user_account(id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_token_user ON refresh_token(user_account_id);
CREATE INDEX idx_refresh_token_expires ON refresh_token(expires_at);