-- =========================
-- USER_ACCOUNT
-- =========================
CREATE TABLE USER_ACCOUNT
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    GITHUB_USER_ID    BIGINT       NOT NULL UNIQUE,
    GITHUB_LOGIN      VARCHAR(100) NOT NULL UNIQUE,
    GITHUB_EMAIL      VARCHAR(150) NULL,
    GITHUB_AVATAR_URL VARCHAR(255) NULL,
    GITHUB_NAME       VARCHAR(100) NULL,
    LAST_SYNCED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IDX_GITHUB_LOGIN
    ON USER_ACCOUNT (GITHUB_LOGIN);


-- =========================
-- ACCESS_TOKEN
-- =========================
CREATE TABLE ACCESS_TOKEN
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ACCOUNT_ID BIGINT       NOT NULL,
    ACCESS_TOKEN    VARCHAR(255) NOT NULL UNIQUE,
    TOKEN_TYPE      VARCHAR(20)  DEFAULT 'BEARER',
    SCOPE           VARCHAR(500) NULL,
    EXPIRES_AT      TIMESTAMP    NULL,
    CREATED_AT      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_ACCESS_TOKEN_USER
        FOREIGN KEY (USER_ACCOUNT_ID)
            REFERENCES USER_ACCOUNT (ID)
            ON DELETE CASCADE
);

CREATE INDEX IDX_TOKEN_USER
    ON ACCESS_TOKEN (USER_ACCOUNT_ID);


-- =========================
-- GITHUB_REPO
-- =========================
CREATE TABLE GITHUB_REPO
(
    ID                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ACCOUNT_ID       BIGINT NOT NULL,
    GITHUB_REPO_ID        BIGINT NOT NULL UNIQUE,
    GITHUB_REPO_NAME      VARCHAR(100) NOT NULL,
    GITHUB_REPO_FULL_NAME VARCHAR(200) NOT NULL UNIQUE,
    DEFAULT_BRANCH        VARCHAR(150) NULL,
    DESCRIPTION           TEXT NULL,
    GITHUB_REPO_URL       VARCHAR(255) NULL,
    IS_PRIVATE            TINYINT(1) NOT NULL DEFAULT 0,
    LAST_SYNCED_AT        TIMESTAMP NULL,
    CREATED_AT            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT            TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_GITHUB_REPOSITORY_OWNER
        FOREIGN KEY (USER_ACCOUNT_ID)
            REFERENCES USER_ACCOUNT (ID)
            ON DELETE CASCADE
);

CREATE INDEX IDX_REPOSITORY_OWNER
    ON GITHUB_REPO (USER_ACCOUNT_ID);

CREATE INDEX IDX_REPOSITORY_SYNC_TIME
    ON GITHUB_REPO (LAST_SYNCED_AT);


-- =========================
-- COMMIT_LOG
-- =========================
CREATE TABLE COMMIT_LOG
(
    ID                     BIGINT AUTO_INCREMENT PRIMARY KEY,
    GITHUB_REPO_ID         BIGINT    NOT NULL,
    USER_ACCOUNT_ID        BIGINT    NOT NULL,
    GITHUB_COMMIT_SHA      CHAR(40)  NOT NULL,
    COMMITTED_AT           TIMESTAMP NOT NULL,
    MESSAGE                TEXT      NOT NULL,
    HTML_URL               VARCHAR(255) NULL,
    ADDITIONS              BIGINT    DEFAULT 0,
    DELETIONS              BIGINT    DEFAULT 0,
    TOTAL_CHANGES          BIGINT    DEFAULT 0,
    FILES_CHANGED          BIGINT    NULL,
    CREATED_AT             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT             TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_COMMIT_REPO
        FOREIGN KEY (GITHUB_REPO_ID)
            REFERENCES GITHUB_REPO (ID)
            ON DELETE CASCADE,

    CONSTRAINT FK_COMMIT_AUTHOR
        FOREIGN KEY (USER_ACCOUNT_ID)
            REFERENCES USER_ACCOUNT (ID)
            ON DELETE CASCADE,

    CONSTRAINT UK_COMMIT_REPO_SHA
        UNIQUE (GITHUB_REPO_ID, GITHUB_COMMIT_SHA)
);

CREATE INDEX IDX_COMMIT_AUTHOR_TIME
    ON COMMIT_LOG (USER_ACCOUNT_ID, COMMITTED_AT);

CREATE INDEX IDX_COMMIT_REPO_TIME
    ON COMMIT_LOG (GITHUB_REPO_ID, COMMITTED_AT);


-- =========================
-- COMMIT_FILE_CHANGE
-- =========================
CREATE TABLE COMMIT_FILE_CHANGE
(
    ID                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    COMMIT_LOG_ID         BIGINT       NOT NULL,
    FILENAME              VARCHAR(500) NOT NULL,
    PREV_FILENAME         VARCHAR(500) NULL,
    STATUS                VARCHAR(20)  NOT NULL,
    ADDITIONS             BIGINT       NOT NULL DEFAULT 0,
    DELETIONS             BIGINT       NOT NULL DEFAULT 0,
    CHANGES               BIGINT       NOT NULL DEFAULT 0,
    PATCH                 LONGTEXT NULL,
    CREATED_AT            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT            TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_COMMIT_FILE_COMMIT
        FOREIGN KEY (COMMIT_LOG_ID)
            REFERENCES COMMIT_LOG (ID)
            ON DELETE CASCADE,

    CONSTRAINT CHK_FILE_STATUS
        CHECK (STATUS IN ('ADDED','MODIFIED','REMOVED','RENAMED'))
);

CREATE INDEX IDX_FILE_COMMIT
    ON COMMIT_FILE_CHANGE (COMMIT_LOG_ID);

CREATE INDEX IDX_FILE_FILENAME
    ON COMMIT_FILE_CHANGE (FILENAME);


-- =========================
-- COMMIT_ANALYSIS
-- =========================
CREATE TABLE COMMIT_ANALYSIS
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    COMMIT_LOG_ID      BIGINT NOT NULL UNIQUE,
    FLAGGED_COUNT      BIGINT NOT NULL DEFAULT 0,
    SWEAR_COUNT        BIGINT NOT NULL DEFAULT 0,
    EXCLAIM_COUNT      BIGINT NOT NULL DEFAULT 0,
    EMOJI_COUNT        BIGINT NOT NULL DEFAULT 0,
    SENTIMENT          VARCHAR(20) NULL,
    SENTIMENT_SCORE    DECIMAL(5, 2) NULL,
    ANALYZED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_COMMIT_ANALYSIS_COMMIT
        FOREIGN KEY (COMMIT_LOG_ID)
            REFERENCES COMMIT_LOG (ID)
            ON DELETE CASCADE,

    CONSTRAINT CHK_SENTIMENT
        CHECK (SENTIMENT IN ('POSITIVE','NEUTRAL','NEGATIVE'))
);


-- =========================
-- FLAGGED_TOKEN
-- =========================
CREATE TABLE FLAGGED_TOKEN
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    COMMIT_LOG_ID    BIGINT       NOT NULL,
    TOKEN            VARCHAR(200) NOT NULL,
    TOKEN_TYPE       VARCHAR(20)  NOT NULL DEFAULT 'OTHER',
    WEIGHT           BIGINT       NOT NULL DEFAULT 1,
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_FLAGGED_TOKEN_COMMIT
        FOREIGN KEY (COMMIT_LOG_ID)
            REFERENCES COMMIT_LOG (ID)
            ON DELETE CASCADE,

    CONSTRAINT UK_COMMIT_TOKEN
        UNIQUE (COMMIT_LOG_ID, TOKEN, TOKEN_TYPE),

    CONSTRAINT CHK_TOKEN_TYPE
        CHECK (TOKEN_TYPE IN ('SWEAR','SLANG','EMOJI','EMPHASIS','OTHER'))
);

CREATE INDEX IDX_FLAGGED_COMMIT
    ON FLAGGED_TOKEN (COMMIT_LOG_ID);

CREATE INDEX IDX_FLAGGED_TOKEN_TYPE
    ON FLAGGED_TOKEN (TOKEN_TYPE);